### ISSUE TITLE
Setting get randomized when exporting

### ISSUE THREAD

**Issue by korrawe** [DART2022/DART#1]
Hi, 
Thank you for the great work.

I have tried to use the Unity executable GUI to generate new data and have some questions:
- When I tried to export the data by setting "picture count" to 1 (or anything >0), the GUI randomized all the settings again instead of using the one I set. Is this intended?
- What I tried to do is to create a few poses with the same identity and the same lighting, is there any way to achieve this? Maybe, just a method to export the example animation with any selected identity would be great.
- As there might be a few considerations when creating a new dataset (as mentioned above), do you plan to release a more programmable version of the GUI? I think even the code without GUI would be very useful for the community.

Best.

**Comment by DART2022** [comment]
Hi korrawe,

Good to hear advice from you! The exporting process with `picture count` > 0 serves to generate the posed hand under random illumination, background, and accessories.

The second purpose seems important and for your customizable need. I would like to open the Unity GUI code in the coming few days.

Best,
Daiheng
Best..

**Comment by korrawe** [comment]
Hi Daiheng,

Thank you for your quick reply.
At the moment, is there any way to export just a single frame with the options that I select? It does not seem like the image is exported when the picture count is 0 (only the xls file is generated). Am I missing something?

Best,
Korrawe

**Comment by tomguluson92** [comment]
> Hi Daiheng,
> 
> Thank you for your quick reply. At the moment, is there any way to export just a single frame with the options that I select? It does not seem like the image is exported when the picture count is 0 (only the xls file is generated). Am I missing something?
> 
> Best, Korrawe

Hi Korrawe, I have open-sourced the GUI source code, please refer to the README and download it.
