### ISSUE TITLE
Fine-grained classification tags

### ISSUE THREAD

**Issue by walsvid** [DART2022/DART#10]
Hi authors, thank you for your great work.

I wonder if DARTset data has annotation files for finer grained semantic description of each sample. For example, whether the hand corresponding to a certain picture has accessories, what kind of skin color and other semantic labels. 

I notice that the pkl file contains ['pose', 'joint3d', 'vertex', 'joint2d', 'img'], but no other tags. 

For example, as it in the "Ablation Study On Accessories" in the paper, you have report the statistics on w/o. Acs and w/ O. Acs and their respective performance improvements.

I wonder how to select sub-dataset with different attributes quickly?

**Comment by tomguluson92** [comment]
Hi @walsvid , thanks for your interests. The ablation study we conduct is on mano pose sampled from Freihand and do not publicly included in DARTset. For you interest, I guess you could generate your own data from the Unity code and may be you need to revise it a little bit.
