### ISSUE TITLE
How to get your DARTset?

### ISSUE THREAD

**Issue by Divenirelrn** [DART2022/DART#12]
Thx for your great work. I am working on 3d hand pose estimation, and want to make a dataset just like your DARTset. I can get images and excels with UNITY GUI, but after that, I don't know the process of converting them to the format of DARTset.  Could you please describe the process?

**Comment by tomguluson92** [comment]
Hi there, you can check `https://github.com/DART2022/DART/tree/master/postprocess` for convert data to MANO

**Comment by Divenirelrn** [comment]
I use convert.py in https://github.com/DART2022/DART/tree/master/postprocess to convert the data generated by UNITY GUI to output.pkl, then I plot "joints_2d" and "ortho_intr" using DARTset.py(https://github.com/DART2022/DART/tree/master/DARTset.py), but they are not equal. However, when I plot "joints_2d" and "ortho_intr" of your DARTset using DARTset.py, they are nearly equal. Could you please tell me the reason?

**Comment by YuliangXiu** [comment]
[2024.04.01] **DARTset could be easily cloned from Huggingface/Dataset** at [DARTset](https://huggingface.co/datasets/Yuliang/DART)
