### ISSUE TITLE
Curious about licensing

### ISSUE THREAD

**Issue by moshimeow** [DART2022/DART#2]
Hi! I work for Collabora on open-source hand tracking, and for the past little while I've been struggling to publish our own artificial dataset (basically the same idea as yours tbh) because of licensing issues. 

I know that it's too hard to get commercial licenses for MANO, but what about the textures you've published? What's their license, and can they be used commercially?

(FWIW, note that although we are doing this work commercially, we're publishing all of it as FOSS that you can do whatever you want with. Mostly in https://gitlab.freedesktop.org/monado/utilities/hand-tracking-playground/ and https://gitlab.freedesktop.org/monado/monado/-/tree/main/src/xrt/tracking/hand/mercury)

**Comment by tomguluson92** [comment]
Hi!
We have negotiated with Meshcapade about the MANO license and got granted since then. From my experience,
I think R&D license is enough for DART.

Your work seems fascinating to me, we can have a deeper negotiation through email: my personal email is `samuel.gao023@gmail.com`.
