### ISSUE TITLE
Dropbox url is 404

### ISSUE THREAD

**Issue by codytackson** [DART2022/DART#3]
Hi @DART2022 ,
Thanks for this great job! the download url of dataset at dropbox is 404 at my side, could you check this? Thank You!

**Comment by tomguluson92** [comment]
Hi Cody,
    I fix it, please check the README.

**Comment by codytackson** [comment]
Hi @tomguluson92 ,
Thanks for fixing this. I tried to download the zip files in train folder via several net environments and machines but cannot download them successfully. It alway raises "Unknown server error".  May I bother you to uploading the dataset to Google Drive, TIA

**Comment by tomguluson92** [comment]
> Hi @tomguluson92 , Thanks for fixing this. I tried to download the zip files in train folder via several net environments and machines but cannot download them successfully. It alway raises "Unknown server error". May I bother you to uploading the dataset to Google Drive, TIA

Hi Cody, I have tested downloading the zip file. All works well,
I guess you may need an VPN?

![image](https://user-images.githubusercontent.com/19585240/196839785-aebb3879-a989-4b0c-bfaf-ed5ce2160e42.png)

**Comment by codytackson** [comment]
Yeah It works smoothly at the beginning but crashes when downloading about 20% to 80%

**Comment by YuliangXiu** [comment]
[2024.04.01] **DARTset could be easily cloned from Huggingface/Dataset** at [DARTset](https://huggingface.co/datasets/Yuliang/DART)
