### ISSUE TITLE
Details about MANO extension

### ISSUE THREAD

**Issue by codytackson** [DART2022/DART#4]
Hi @DART2022 ,

Thanks for sharing ideas and code with us. I am confused about the pseudo code of alignment process in Fig. 2a. The code seems only extend the dimension of W, P and R and leaf out the wrist part as zero.  My questions are:

1. Do we need to  run LBS after this pseudo code ?
2.  How can we convert the \theta and \beta from MANO  to the new parameters of DART?

Thanks.

**Comment by tomguluson92** [comment]
For compatibility's sake,  the \theta and \beta can be used directly to drive the original MANO or DART.
