### ISSUE TITLE
Data Generation.

### ISSUE THREAD

**Issue by Hermeskid123** [DART2022/DART#7]
is there a way to use the GUI to generate data so its in the same format as the DART dateset.

**Comment by tomguluson92** [comment]
Hi, you may need to adjust the source GUI unity code so as to achieve this. We have a `batch` version for yielding the data as depicted in DARTset in parallel.

**Comment by gs-ren** [comment]
Hi， I find the another hand is not included, how can I generate left hand data? @tomguluson92

**Comment by tomguluson92** [comment]
Hi @gs-ren 
Since DART only extends the right hand of MANO in this process, we are not involving the left hand for now. 
This is because, in reality, the rendered image can be horizontally flipped to generate a so-called left-handed image.
