### ISSUE TITLE
Finger penetration issue in the dataset

### ISSUE THREAD

**Issue by xmlyqing00** [DART2022/DART#8]
Hi,

Thanks for providing such a large hand dataset. May I ask about the pose code format in the released dataset? It seems that they're in the MANO format. which is different from the paper that says you generate hand pose by A-MANO. I used the MANO decoder to decode the hand pose to mesh but found finger penetration issues. And some poses look unnatural.

Thanks for your time!!!

![image](https://user-images.githubusercontent.com/8945602/232279045-f9157d57-691a-4539-a352-a61a8a0a489e.png)
![image](https://user-images.githubusercontent.com/8945602/232279060-ab8a3b6e-db35-4b03-9834-84c3df402557.png)
![image](https://user-images.githubusercontent.com/8945602/232279097-1ca5e342-7037-45fc-8b83-9346b89a5388.png)

**Comment by tomguluson92** [comment]
Hi @xmlyqing00 , Thanks for you mention this problem. We do some pose adaptation as to fit with the code we use in `DARTset.py`. Please use that code for any comparison and things like that.

**Comment by lixiny** [comment]
@xmlyqing00 May I ask how are the parameters configured for your MANO layer?


I suggest that using the ManoLayer from [manotorch](https://github.com/lixiny/manotorch) package with the following parameters:


```
ManoLayer(
    joint_rot_mode="axisang",
    use_pca=False,
    mano_assets_root="assets/mano_v1_2",
    center_idx=0,
    flat_hand_mean=False
)
```

and check whether these issues still persist?

**Comment by xmlyqing00** [comment]
Hi,
I used the wrong decoder to decode the hand code. Now the penetration problem is not an issue. Thanks for your help!

Best
