### ISSUE TITLE
关于坐标系的问题

### ISSUE THREAD

**Issue by liangzhenghao2000** [DART2022/DART#9]
我想问一下数据里存的raw_mano_param是哪个坐标系下的，是unity（z轴朝相机朝向）下的还是渲染坐标系（z轴朝相机朝向的反方向）下的？

**Comment by tomguluson92** [comment]
Hello, 请check`https://github.com/DART2022/DART/blob/master/DARTset.py#L196`

**Comment by liangzhenghao2000** [comment]
> Hello, 请check`https://github.com/DART2022/DART/blob/master/DARTset.py#L196`

我看到代码上注释写的是从UNITY坐标系转到OpenGL坐标系（DARTset.py第94和第103行），但是却又将手中心移到了[0, 0, 0.5]的位置（DARTset.py第98和第107行），如果是OpenGL坐标系[0, 0, 0.5]应该是在相机背面？
